version: '3'

services:
  client:
    image: cedardevs/onestop-client:latest
    ports:
      - 8080:80
    depends_on:
      - api-search
      - geoportal-search
    environment:
      - "ONESTOP_ENDPOINT=api-search:8097"
      - "GEOPORTAL_ENDPOINT=geoportal-search:8080"

  api-search:
    image: cedardevs/onestop-api-search:latest
    ports:
      - 8097:8097
    depends_on:
      - elasticsearch
    environment:
      - elasticsearch_host=elasticsearch
      - elasticsearch_port=9200
      - logging_level_org.cedar.onestop.api=DEBUG

  api-metadata:
    image: cedardevs/onestop-api-metadata:latest
    ports:
      - 8098:8098
    depends_on:
      - elasticsearch
    environment:
      - elasticsearch_host=elasticsearch
      - elasticsearch_port=9200
      - logging_level_org.cedar.onestop.api=DEBUG

  geoportal-search:
    image: cedardevs/onestop-geoportal-search:latest
    depends_on:
      - elasticsearch
    ports:
      - 8080
    environment:
      - "ELASTICSEARCH_ENDPOINT=http://elasticsearch:9200/search/granule/_search"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION:-5.5.3}
    environment:
      - xpack.security.enabled=false
    ports:
      - 9300:9300
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:${ES_VERSION:-5.5.3}
    ports:
      - 5601:5601
