apiVersion: v1
description: A Helm chart to spin up the development tools of OneStop
name: onestop-dev
version: 0.3.0

dependencies:
  - name: nginx-ingress
    version: ~1.1.4
    repository: "@stable"
  - name: cp-helm-charts
    version: ~0.1.0
    repository: https://confluentinc.github.io/cp-helm-charts/
  - name: prometheus
    version: ~8.7.0
    repository: "@stable"
  - name: grafana
    version: ~1.26.1
    repository: "@stable"
  - name: metrics-server
    version: ~2.8.7
    repository: "@stable"
  - name: cas
    version: ~0.1.0
    repository: file://../cas
    condition: cas.enabled
