onestop-client:
  enabled: true
onestop-indexer:
  enabled: true
onestop-parsalyzer:
  enabled: true
onestop-registry:
  enabled: true
onestop-search:
  enabled: true
onestop-user:
  enabled: false # TODO - enable when implemented
