onestop-admin:
  keystore:
    file: "/etc/onestop-admin/sciapps-keystore.jks"
  spring:
    profiles:
      active: "securityenabled,kafkadisabled"
  logging.level: DEBUG
  etl.sitemap.delay.initial: "60000"

onestop-search:
  auth:
    clientId: "urn:gov:gsa:openidconnect.profiles:sp:sso:NOAA:SciAppsOneStop"
    allowedOrigin: "https://sciapps.colorado.edu"
    endpoints:
      loginSuccessRedirect: "/"
      loginFailureRedirect: "/"
      logoutSuccessRedirect: "/"
    keystoreFile: "/etc/onestop-search/logingov.jks"
  # elasticsearch:
  #   host: "elasticsearch"
  #   port: "9200"

# values used within cp-helm-charts
cp-helm-charts:
  cp-zookeeper:
    servers: 1
    jmx:
      port:
    prometheus:
      jmx:
        enabled:
          false
  cp-kafka:
    brokers: 1
    jmx:
      port:
    prometheus:
      jmx:
        enabled:
          false
  cp-schema-registry:
    jmx:
      port:
    prometheus:
      jmx:
        enabled:
          false

# disables dependencies on unused subcharts from confluent platform
cp-kafka-rest:
  enabled: false
cp-kafka-connect:
  enabled: false
cp-ksql-server:
  enabled: false