server:
  port: 8098
  context-path: /onestop/api

spring:
  application:
    name: onestop-metadata-api

logging:
  level:
      org.cedar.onestop.api.search: INFO
      org.gradle: WARN
      org.apache.http: WARN
      org.apache.http.wire: WARN
      org.apache.http.headers: WARN
      groovyx.net.http: WARN
      groovyx.net.http.HttpURLClient: WARN
      org.springframework: INFO
      org.springframework.amqp: WARN
      org.hibernate: WARN

elasticsearch:
  version: ${esVersion}
  host: localhost
  port: 9200
  max-tasks: 10
  index:
    universal-type: doc
    search:
      collection:
        name: search_collection
        pipeline-name: collection_pipeline
      granule:
        name: search_granule
        pipeline-name: granule_pipeline
    staging:
      collection:
        name: staging_collection
      granule:
        name: staging_granule

info.version: ${version}
