features.secure.upload: true
features.secure.authorization: true
features.basicAuth.disabled: false

roles.names: ADMIN;USER
user.roles: elliott.richerson@noaa.gov:ADMIN;david.neufeld@noaa.gov:ADMIN

server:
  ssl:
    key-alias: ${KEYSTORE_ALIAS}
    #key-password: ${KEY_PASSWORD}
    enabled-protocols: TLSv1.2
    protocol: TLS
    enabled: true
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store: /etc/api-metadata/keystore.jks
    key-store-type: JKS

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  # h2.console.enabled: true
  # h2.console.path: /h2-console
  datasource:
    # url: jdbc:h2:mem:testdb;TRACE_LEVEL_FILE=4;DB_CLOSE_ON_EXIT=FALSE # pipes logging output for h2 to console
    # url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    # driverClassName: org.h2.Driver
    #  DERBY:
    # url: jdbc:derby:memory:myDb;create=true
    # driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    # hqsql
    url: jdbc:hsqldb:mem:myDb
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    # squlite
    # driverClassName: org.sqlite.JDBC
    # url: jdbc:sqlite:memory:myDb
    username: sa # default username
    password:
  jpa:
    hibernate.ddl-auto: none
    # database-platform: org.hibernate.dialect.H2Dialect
    properties:
      show_sql: true
      format_sql: true
  liquibase:
    enabled: true # set to false if we don't want to run and check migrations on startup
    default-schema: PUBLIC # default schema for H2, here for documentation


# SAML Identity Provider Configuration
# Note: for cu-server-admin, this config will be replaced by the
#   proper 'sciapps' endpoint version of the identity provider info
#   the production endpoint would similarly need to override this section
# -----------------------------------------------------------------
# ICAM (localhost)
# -----------------------------------------------------------------
identityprovider:
  name: "ICAM (localhost)"
  loginEndpoint: "https://sso-dev.lb.csp.noaa.gov:443/openam/SSOPOST/metaAlias/noaa-online/noaa-online-idp"
  loginBinding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
  logoutEndpoint: "https://sso-dev.lb.csp.noaa.gov:443/openam/IDPSloRedirect/metaAlias/noaa-online/noaa-online-idp"
  logoutBinding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
  issuerSP: "https://localhost:30098/onestop/admin/"
  issuerIDP: "noaa-online-idp"
  authnContextRefs:
    - "urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified"
  authnContextComparisonType: "minimum"
  assertionConsumerServiceURL: "https://localhost:30098/onestop/admin/loginConsume"
  assertionConsumerServiceLogoutURL: "https://localhost:30098/onestop/admin/logoutConsume"
  nameIDPolicyFormat: "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
  signatureAlgorithm: "http://www.w3.org/2000/09/xmldsig#rsa-sha1"
  signatureCanonicalizationAlgorithm: "http://www.w3.org/2001/10/xml-exc-c14n#"
  digestAlgorithm: "http://www.w3.org/2000/09/xmldsig#sha1"
  emailAssertionName: "mail"
  uuidAssertionName: "uid"
