---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    tier: "backend"
    devmode: "true"
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
      nodePort: 30092
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  labels:
    tier: "backend"
    devmode: "true"
spec:
  selector:
    app: elasticsearch
  ports:
    - name: transport
      port: 9300
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    tier: "backend"
    devmode: "true"
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      restartPolicy: Always
      initContainers:
      - name: init-sysctl
        image: busybox:1
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: init-volume
        image: busybox:1
        command: ["chown", "-v", "1000:1000", "/data" ]
        volumeMounts:
        - name: storage
          mountPath: "/data"
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.14 # use gradle ${ES_VERSION:-5.6.14} in future
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 512Mi
        env:
        - name: cluster.name
          value: elasticsearch # default name; should be variable in prod
        - name: discovery.zen.ping.unicast.hosts
          value: elasticsearch-discovery
        - name: discovery.zen.minimum_master_nodes
          value: "1" # should be set to (replicas / 2) + 1
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m # may need more memory
#        - name: bootstrap.memory_lock
#          value: "true"
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.watcher.enabled
          value: "false"
        - name: xpack.monitoring.enabled
          value: "false"
        - name: xpack.ml.enabled
          value: "false"
        - name: xpack.graph.enabled
          value: "false"
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: storage
          mountPath: "/usr/share/elasticsearch/data"
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
