---
apiVersion: v1
kind: Service
metadata:
  name: onestop-geoportal-search
  labels:
    environment: dev
    tier: "backend"
    devmode: "true"
spec:
  selector:
    app: onestop-geoportal-search
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onestop-geoportal-search
  labels:
    tier: "backend"
    devmode: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onestop-geoportal-search
  template:
    metadata:
      labels:
        app: onestop-geoportal-search
    spec:
      restartPolicy: Always
      containers:
      - name: onestop-geoportal-search
        image: cedardevs/onestop-geoportal-search:latest
        env:
        - name: ELASTICSEARCH_ENDPOINT
          value: http://elasticsearch:9200/search/granule/_search
        ports:
        - containerPort: 8080
          name: http
