---
apiVersion: v1
kind: Service
metadata:
  name: onestop-api-search
  labels:
    environment: dev
    tier: "backend"
    devmode: "true"
spec:
  selector:
    app: onestop-api-search
  ports:
    - name: http
      port: 8097
      nodePort: 30097
  type: NodePort
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onestop-api-search
  labels:
    tier: "backend"
    devmode: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onestop-api-search
  template:
    metadata:
      labels:
        app: onestop-api-search
    spec:
      containers:
      - name: onestop-api-search
        image: cedardevs/onestop-api-search
        env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: LOGGING_LEVEL_ORG.CEDAR.ONESTOP.API
          value: DEBUG
        - name: SPRING.CONFIG.ADDITIONAL-LOCATION
          value: /deployments/config/application.yaml
        volumeMounts:
        - name: application-config
          mountPath: "/deployments/config"
          readOnly: true
        ports:
        - containerPort: 8097
      volumes:
      - name: application-config
        configMap:
          name: onestop-search-api-config
          items:
          - key: application.yaml
            path: application.yaml
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: onestop-search-api-config
  labels:
    tier: "backend"
    devmode: "true"
data:
  application.yaml: |
    ui:
      banner:
        message: DEMO - This site is not running on NCEI hardware, does not contain NCEI's full data holdings, and contains a limited set of its intended functionality.
      featured:
          - title: GOES Data
            searchTerm: '"Gridded Satellite GOES"'
            imageUrl: "https://www.ncdc.noaa.gov/gridsat/images/sample.png"
          - title: Digital Elevation Models
            searchTerm: '"digital elevation"'
            imageUrl: "https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_global_mosaic_hillshade/ImageServer/exportImage?bbox=-170.95,-14.40,-170.45,-14.18&size=500,500&format=png32&interpolation=%20RSP_BilinearInterpolation&renderingRule=%7B%22rasterFunction%22:%22ColorHillshade%22%7D&f=image"
          - title: NWLON and PORTS
            searchTerm: +nwlon +ports
            imageUrl: "https://data.nodc.noaa.gov/cgi-bin/gfx?id=gov.noaa.nodc:NDBC-COOPS"
          - title: Climate Data Record (CDR)
            searchTerm: '"NOAA Climate Data Record"'
            imageUrl: "https://www.ncdc.noaa.gov/sites/default/files/styles/cdr-full-width/public/cdr/AVHRRSurfaceReflectance.png"
