apiVersion: v1
kind: Service
metadata:
  name: onestop-client
  labels:
    environment: dev
    tier: frontend
spec:
  selector:
    app: onestop-client
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onestop-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onestop-client
  template:
    metadata:
      labels:
        app: onestop-client
    spec:
      restartPolicy: Always
      containers:
      - name: onestop-client
        image: cedardevs/onestop-client:2.0.0-RC8-SNAPSHOT
        env:
        - name: ONESTOP_ENDPOINT
          value: onestop-api-search:8097
        - name: GEOPORTAL_ENDPOINT
          value: onestop-geoportal-search:8080
        ports:
        - containerPort: 80
          name: http
