apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}-transport
  labels:
    app.kubernetes.io/name: {{ include "elasticsearch.name" . }}
    helm.sh/chart: {{ include "elasticsearch.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: 9300
      targetPort: transport
      protocol: TCP
      name: transport
  selector:
    app.kubernetes.io/name: {{ include "elasticsearch.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
