apiVersion: v1
entries:
  psi:
  - apiVersion: v1
    appVersion: 0.2.0
    created: 2019-02-14T17:00:52.380465-07:00
    description: A Helm chart for the Persistent Streaming Inventory system
    digest: d3c763a765e247704f2bf25abb386589e157f396a7afe376d746d6542a6ee91b
    name: psi
    urls:
    - psi/psi-0.2.0.tgz
    version: 0.2.0
generated: 2019-02-14T17:00:52.373321-07:00
