openapi: 3.0.0
servers:
  - url: 'https://sciapps.colorado.edu/onestop/api'
    description: Development test server (uses test data)
  - url: 'https://data.noaa.gov/onestop/api/search'
    description: NOAA OneStop
info:
  title: OneStop Search API
  description: 'Search Collections and Granules! More information on search request and responses available at [Search API Requests](https://github.com/cedardevs/onestop/wiki/OneStop-Search-API-Requests) and [Search API Responses](https://github.com/cedardevs/onestop/wiki/OneStop-Search-API-Responses).'
  version: 2.4.0
tags:
  - name: collection
    description: Discover available collections of data.
  - name: granule
    description: Discover available files of data.
  - name: flattened-granule
    description: Flattened granules are a representation of the granules which inherit all the metadata from the parent collection.
paths:
  /collection:
    head:
      tags:
        - collection
      summary: Get Collection Info
      responses:
        '200':
          description: Successful operation
    get:
      tags:
        - collection
      summary: Get Collection Info
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: 'response.json#/infoResponse'
  '/collection/{id}':
    head:
      tags:
        - collection
      summary: Collection by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID of the collection
      responses:
        '200':
          description: Successful operation
        '404':
          description: Request Parsing Error
    get:
      tags:
        - collection
      summary: Collection by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID of the collection
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fullCollectionResponse'
        '404':
          description: Request Parsing Error
  /search/collection:
    post:
      tags:
        - collection
      summary: Retrieve collection metadata
      description: 'Retrieve collection metadata records matching the text query string, spatial, and/or temporal filter.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: request.json
              externalDocs:
                example.com
            examples:
              payload0:
                $ref: '#/components/examples/payload0'
              payload1:
                $ref: '#/components/examples/payload1'
              payload2:
                $ref: '#/components/examples/payload2'
              payload3:
                $ref: '#/components/examples/payload3'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: 'response.json#/searchResponse'
        '400':
          description: Bad Request
  /granule:
    head:
      tags:
        - granule
      summary: Get Granule Info
      responses:
        '200':
          description: Successful operation
    get:
      tags:
        - granule
      summary: Get Granule Info
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: 'response.json#/infoResponse'
  '/granule/{id}':
    head:
      tags:
        - granule
      summary: Granule by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID of the granule
      responses:
        '200':
          description: Successful operation
        '404':
          description: Request Parsing Error
    get:
      tags:
        - granule
      summary: Granule by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID of the granule
      responses:
        '200':
          description: Successful operation
        '404':
          description: Request Parsing Error
  /search/granule:
    post:
      tags:
        - granule
      summary: Retrieve granule metadata
      description: 'Retrieve granule metadata records matching the text query string, spatial, and/or temporal filter.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: request.json
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: 'response.json#/searchResponse'
        '400':
          description: Bad Request
  /flattened-granule:
    head:
      tags:
        - flattened-granule
      summary: Get Flattened Granule Info
      responses:
        '200':
          description: Successful operation
    get:
      tags:
        - flattened-granule
      summary: Get Flattened Granule Info
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: 'response.json#/infoResponse'
  '/flattened-granule/{id}':
    head:
      tags:
        - flattened-granule
      summary: Flattened Granule by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID of the flattened granule
      responses:
        '200':
          description: Successful operation
        '404':
          description: Request Parsing Error
    get:
      tags:
        - flattened-granule
      summary: Flattened Granule by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID of the flattened granule
      responses:
        '200':
          description: Successful operation
        '404':
          description: Request Parsing Error
  /search/flattened-granule:
    post:
      tags:
        - flattened-granule
      summary: Retrieve flattened granule metadata
      description: 'Retrieve flattened granule metadata records matching the text query string, spatial, and/or temporal filter.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: request.json
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: 'response.json#/searchResponse'
        '400':
          description: Bad Request
components:
  schemas:
    fullCollectionResponse:
      description: Collection
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/collectionMetadataObject'
        data:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/collectionDataObject'
    collectionMetadataObject:
      type: object
      properties:
        totalGranules:
          type: integer
    collectionDataObject:
      type: object
      properties:
        type:
          type: string
          enum:
            - collection
        id:
          type: string
  examples:
    payload0:
      value:
        queries:
          - type: queryText
            value: climate
        filters: []
        facets: true
        page:
          max: 20
          offset: 0
      summary: basic text query
    payload1:
      value:
        queries:
          - type: queryText
            value: weather
        filters:
          - type: facet
            name: science
            values:
              - Agriculture
              - Atmosphere > Atmospheric Radiation > Incoming Solar Radiation
        facets: true
        page:
          max: 20
          offset: 0
      summary: multiple science theme filters selected
    payload2:
      value:
        queries:
          - type: queryText
            value: weather
        filters:
          - type: facet
            name: science
            values:
              - Agriculture
          - type: facet
            name: instruments
            values:
              - ADCP > Acoustic Doppler Current Profiler
        facets: true
        page:
          max: 20
          offset: 0
      summary: multiple facets selected
    payload3:
      value:
        queries:
          - type: queryText
            value: weather
        filters: []
        facets: false
        page:
          max: 20
          offset: 20
      summary: Next Page request
